-- Shared Hyprland experiment. Machine-specific output policy is generated by
-- Home Manager immediately above this file.
local ipc = "noctalia-shell ipc call"

hl.config({
	general = {
		gaps_in = 5,
		gaps_out = 12,
		border_size = 2,
		layout = "dwindle",
		resize_on_border = true,
		col = {
			active_border = "rgba(d79921ff)",
			inactive_border = "rgba(504945cc)",
		},
	},
	decoration = {
		rounding = 10,
		shadow = {
			enabled = true,
			range = 4,
			color = "rgba(1d2021ee)",
		},
		blur = {
			enabled = true,
			size = 3,
			passes = 2,
		},
	},
	input = {
		kb_layout = "us",
		numlock_by_default = true,
	},
	misc = {
		disable_hyprland_logo = true,
		force_default_wallpaper = 0,
	},
	dwindle = {
		preserve_split = true,
	},
})

hl.layer_rule({
	name = "noctalia",
	match = { namespace = "noctalia-background-.*$" },
	ignore_alpha = 0.5,
	blur = true,
	blur_popups = true,
})

hl.on("hyprland.start", function()
	hl.exec_cmd("noctalia-shell")
	hl.exec_cmd(start_polkit_agent)
end)

hl.bind("SUPER + Return", hl.dsp.exec_cmd("wezterm"))
hl.bind("SUPER + Space", hl.dsp.exec_cmd(ipc .. " launcher toggle"))
hl.bind("SUPER + SHIFT + D", hl.dsp.exec_cmd("fuzzel"))
hl.bind("SUPER + S", hl.dsp.exec_cmd(ipc .. " controlCenter toggle"))
hl.bind("SUPER + comma", hl.dsp.exec_cmd(ipc .. " settings toggle"))
hl.bind("SUPER + SHIFT + E", hl.dsp.exec_cmd(ipc .. " sessionMenu toggle"))
hl.bind("SUPER + E", hl.dsp.exec_cmd("dolphin"))
hl.bind("SUPER + B", hl.dsp.exec_cmd("firefox"))
hl.bind("SUPER + Q", hl.dsp.window.close())
hl.bind("SUPER + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind("SUPER + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind("CTRL + ALT + Delete", hl.dsp.exec_cmd("hyprctl dispatch exit"))

local directions = { H = "l", J = "d", K = "u", L = "r" }
for key, direction in pairs(directions) do
	hl.bind("SUPER + " .. key, hl.dsp.focus({ direction = direction }))
	hl.bind("SUPER + SHIFT + " .. key, hl.dsp.window.move({ direction = direction }))
end

for workspace = 1, 9 do
	hl.bind("SUPER + " .. workspace, hl.dsp.focus({ workspace = workspace }))
	hl.bind("SUPER + SHIFT + " .. workspace, hl.dsp.window.move({ workspace = workspace }))
end

hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { mouse = true })
hl.bind("Print", hl.dsp.exec_cmd("hyprshot -m region"))
hl.bind("CTRL + Print", hl.dsp.exec_cmd("hyprshot -m output"))
hl.bind("ALT + Print", hl.dsp.exec_cmd("hyprshot -m window"))

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd(ipc .. " volume increase"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd(ipc .. " volume decrease"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd(ipc .. " volume muteOutput"), { locked = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd(ipc .. " volume muteInput"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
