-- Shared Hyprland experiment. Machine-specific output policy is generated by
-- Home Manager immediately above this file.
hl.config({
	general = {
		gaps_in = 5,
		gaps_out = 12,
		border_size = 2,
		layout = "dwindle",
		resize_on_border = true,
		col = {
			active_border = "rgba(d79921ff)",
			inactive_border = "rgba(504945cc)",
		},
	},
	decoration = {
		rounding = 10,
		shadow = {
			enabled = true,
			range = 4,
			color = "rgba(1d2021ee)",
		},
		blur = {
			enabled = true,
			size = 3,
			passes = 2,
		},
	},
	input = {
		kb_layout = "us",
		numlock_by_default = true,
	},
	misc = {
		disable_hyprland_logo = true,
		force_default_wallpaper = 0,
	},
	dwindle = {
		preserve_split = true,
	},
})

hl.layer_rule({
	name = "noctalia",
	match = { namespace = "^noctalia-wallpaper.*$" },
	ignore_alpha = 0.5,
	blur = true,
	blur_popups = true,
})

hl.on("hyprland.start", function()
	hl.exec_cmd(start_desktop_shell)
	hl.exec_cmd(start_polkit_agent)
end)

-- Start with Hyprland's upstream bindings so its documentation remains useful,
-- then add the familiar dotfiles aliases on keys that do not conflict.
hl.bind("SUPER + Q", hl.dsp.exec_cmd("alacritty"))
hl.bind("SUPER + C", hl.dsp.window.close())
hl.bind("SUPER + M", hl.dsp.exec_cmd(stop_hyprland_session))
hl.bind("SUPER + E", hl.dsp.exec_cmd("dolphin"))
hl.bind("SUPER + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind("SUPER + R", hl.dsp.exec_cmd(shell_action .. " launcher"))
hl.bind("SUPER + P", hl.dsp.window.pseudo())
hl.bind("SUPER + J", hl.dsp.layout("togglesplit"))

hl.bind("SUPER + Return", hl.dsp.exec_cmd("alacritty"))
hl.bind("SUPER + Space", hl.dsp.exec_cmd(shell_action .. " launcher"))
hl.bind("SUPER + SHIFT + D", hl.dsp.exec_cmd("fuzzel"))
hl.bind("SUPER + A", hl.dsp.exec_cmd(shell_action .. " control-center"))
hl.bind("SUPER + comma", hl.dsp.exec_cmd(shell_action .. " settings"))
hl.bind("SUPER + SHIFT + E", hl.dsp.exec_cmd(shell_action .. " session-menu"))
hl.bind("SUPER + B", hl.dsp.exec_cmd("firefox"))
hl.bind("SUPER + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
-- Hyprland 0.55 parses `hyprctl dispatch` arguments as Lua. UWSM owns this
-- session, so ask UWSM to stop it instead of using the removed legacy exit
-- dispatcher syntax.
hl.bind("CTRL + ALT + Delete", hl.dsp.exec_cmd(stop_hyprland_session))

local directions = { left = "left", down = "down", up = "up", right = "right" }
for key, direction in pairs(directions) do
	hl.bind("SUPER + " .. key, hl.dsp.focus({ direction = direction }))
	hl.bind("SUPER + SHIFT + " .. key, hl.dsp.window.move({ direction = direction }))
end

for workspace = 1, 10 do
	local key = workspace % 10
	hl.bind("SUPER + " .. key, hl.dsp.focus({ workspace = workspace }))
	hl.bind("SUPER + SHIFT + " .. key, hl.dsp.window.move({ workspace = workspace }))
end

hl.bind("SUPER + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind("SUPER + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))
hl.bind("SUPER + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind("SUPER + mouse_up", hl.dsp.focus({ workspace = "e-1" }))
hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { mouse = true })
hl.bind("Print", hl.dsp.exec_cmd("hyprshot -m region"))
hl.bind("CTRL + Print", hl.dsp.exec_cmd("hyprshot -m output"))
hl.bind("ALT + Print", hl.dsp.exec_cmd("hyprshot -m window"))

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd(shell_action .. " volume-up"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd(shell_action .. " volume-down"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd(shell_action .. " volume-mute"), { locked = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd(shell_action .. " mic-mute"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
