model = "gpt-5.6-sol"
check_for_update_on_startup = false
model_reasoning_effort = "xhigh"
personality = "pragmatic"
approval_policy = "never"
sandbox_mode = "danger-full-access"
status_line = ["model-with-reasoning", "current-dir", "fast-mode", "git-branch", "context-remaining"]
plan_mode_reasoning_effort = "xhigh"
service_tier = "fast"

[tui]
notifications = true
web_search = true
theme = "gruvbox-dark"
status_line = ["model-with-reasoning", "current-dir", "context-remaining", "git-branch", "five-hour-limit", "weekly-limit", "task-progress"]

[tui.model_availability_nux]
"gpt-5.5" = 4
"gpt-5.6-sol" = 1

[notice]
hide_gpt5_1_migration_prompt = true
"hide_gpt-5.1-codex-max_migration_prompt" = true
fast_default_opt_out = true
hide_rate_limit_model_nudge = true

[notice.model_migrations]
"gpt-5.1-codex-max" = "gpt-5.2-codex"
"gpt-5.3-codex" = "gpt-5.4"

[features]
memories = true
prevent_idle_sleep = true

[desktop]
conversationDetailMode = "STEPS_COMMANDS"
ambient-suggestions-enabled = true
show-context-window-usage = true
followUpQueueMode = "steer"
keepRemoteControlAwakeWhilePluggedIn = true
browser-annotation-screenshots-mode = "necessary"
appearanceLightCodeThemeId = "gruvbox"
appearanceDarkCodeThemeId = "gruvbox"
usePointerCursors = true
enabled-reasoning-efforts = ["low", "medium", "high", "xhigh", "ultra", "max"]
sansFontSize = 14
codeFontSize = 12

[desktop.appearanceLightChromeTheme]
accent = "#458588"
contrast = 45
ink = "#3c3836"
opaqueWindows = false
surface = "#fbf1c7"

[desktop.appearanceLightChromeTheme.fonts]
code = "BigBlueTerm437 Nerd Font"
ui = "BigBlueTerm437 Nerd Font"

[desktop.appearanceLightChromeTheme.semanticColors]
diffAdded = "#3c3836"
diffRemoved = "#cc241d"
skill = "#b16286"

[desktop.appearanceDarkChromeTheme]
accent = "#458588"
contrast = 60
ink = "#ebdbb2"
opaqueWindows = false
surface = "#282828"

[desktop.appearanceDarkChromeTheme.fonts]
code = "BigBlueTerm437 Nerd Font"
ui = "Satoshi"

[desktop.appearanceDarkChromeTheme.semanticColors]
diffAdded = "#ebdbb2"
diffRemoved = "#cc241d"
skill = "#b16286"

[plugins."cloudflare@openai-curated"]
enabled = true

[plugins."github@openai-curated"]
enabled = true

[plugins."gmail@openai-curated"]
enabled = true

[plugins."remotion@openai-curated"]
enabled = true

[plugins."sendgrid@openai-curated"]
enabled = true

[plugins."stripe@openai-curated"]
enabled = true

[plugins."linear@openai-curated"]
enabled = true

[memories]
use_memories = true
generate_memories = true

[mcp_servers.linear]
url = "https://mcp.linear.app/mcp"
